### ISSUE TITLE
Pictures taken after using the mod are inversely stretched

### ISSUE THREAD

**Issue by jspayd** [fayaz12g/totk-aar#24]
When I use the in-game camera, the pictures produced are stretched. I've included some screenshots to illustrate this. I'm using a resolution of 3440x1440 and emulating with yuzu. I've tried taking pictures with all other mods disabled, and the issue persists then.

![Screenshot (2)](https://github.com/fayaz12g/totk-aar/assets/1097075/075cae1a-28c3-4746-8ecf-6eebc4637a1e)

![Screenshot (3)](https://github.com/fayaz12g/totk-aar/assets/1097075/5ab5eee6-f4af-4ded-a06c-a109f7bb5b46)

**Comment by fayaz12g** [comment]
Yes, the picture is taken of everything you see in the game, however it is saved as 16:9. I actually found a way to fix this by changing the picture viewer to show the full ratio instead of 16:9, but then the default game photos will show stretched. I will speak to fruithaje21 and see what he thinks.

**Comment by Fruithapje21** [comment]
I have stretched the images in the album to their original aspect. Picture panes that only show a preview such as the one in this issue will remain squished for the time being until a better fix is found.

**Comment by fayaz12g** [comment]
A fix for viewing the photos has been applied in 7.0.0
