### ISSUE TITLE
dFPS ini file not being recognized

### ISSUE THREAD

**Issue by fayaz12g** [fayaz12g/totk-aar#42]
I’ve received reports on Reddit that the generated ini file is not being recognized by the dFPS mod. I’m unsure why, but a handtyped identical ini works, so my guess is it’s an invisible formatting issue. I’ll try to fix it, but in the meantime recommend using the premade inis by chucks for resolutions and fps

**Comment by InterClaw** [comment]
A bit off topic maybe but with version 1.5.5 beta 3 I'm not getting any of the premade versions about 1080p to work. They are very fuzzy, so I think it's falling back to 900p.

1080p _does_ work, because I can see that it's sharper, but 1440p, 2160p, 2880p don't.

This is with our without your mod though. Hence OT. 😃 

So what I'm doing now is running with the 1080p version, still use the yuzu 2x scaler, and then just scale it down with bilinear (looks better to me) with no AA.

**Comment by fayaz12g** [comment]
Very interesting, thanks for sharing @InterClaw! dFPS is still very beta so I'm sure it will work better in a future version by Chuck, for now we must wait

**Comment by fayaz12g** [comment]
In the latest beta, dev721b, I included some code that should fix the issue by specifying a default ini and forcing it to be overwritten by a 60.ini file. Unless the way python writes the is causing the issue, it should be fixed. I'll have Chris test it tomorrow.

**Comment by InterClaw** [comment]
It's working!

This, with 1x internally, looks better than the approach above.

**Comment by fayaz12g** [comment]
@InterClaw That is so so great to hear!!! Thank you for testing! I'll have my friend do some more testing with me on Zoom anyways just to make sure everything is working as intended, but I'm glad to hear that passing it in after the default.ini seems to work
