### ISSUE TITLE
Disable Quality Reduction mod not actually loading

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#56]
I was suddenly noticing some pretty jarring FPS drops, like dropping down to 22-23 fps, or even 11 fps, for no apparent reason. GPU power consumption spikes when this happens as well.

After a lot of testing back and forth with various versions, I've determined that this is what happens if "Disable Quality Reduction" is not loaded. At least for me, with the below settings.

![image](https://github.com/fayaz12g/totk-aar/assets/48981208/c85adc91-0d30-4618-a50a-bb9d1b1b9a64)

I've tried this in these versions, which are the recent ones that I can generate.
8.0.1
8.1.1
8.1.4
8.2.0

I tried it without "LOD Improvement", but that had no effect. And I tried it in 8.0.1, because in that version the mod is still under its old name, thinking that maybe that had something to do with it, but nope.

If I put "Disable Quality Reduction" separately in the mod folder, then the problem goes away. This is with or without having included it in AAR mod.

So it seems it's either not getting included in the generation at all, or at least not properly so. Or it's not loading when starting the game for some reason. Is it somehow overwriting itself? But not doing that when running the mod separately? I'm on Yuzu ML 1505 btw.

Or is it the wrong version perhaps? The one I'm using is from the collection [here](https://github.com/HolographicWings/TOTK-Mods-collection/releases), v2.5.1, but I don't think this mod has changed, since it was updated for 1.2.0 a couple of weeks ago.

Speaking of versions, a thought for the new UI, perhaps including the version number (where available) of the mods featured in the tool could be a good idea, so you don't need to guess what you'll be running with. 👍

**Comment by fayaz12g** [comment]
Thank you for the detailed report. After looking at the code, I’m a little confused as to what is wrong. Disable Quality Reduction is literally just one line of code, two hex values (the source and replacement). That line of code is being generated in the pchtxt by the utility, at least on my end. Do you see it in yours? As for version numbers, as it’s just one line of code it doesn’t have versions, it’s never been updated per se, but rather the 1.2.0 version a few weeks ago that was released just changed the register it edits (the first hex value) to the new one given the offset by the version number. I’ll do some more testing and try putting the mod in separate like you mentioned to see if it changes anything.

**Comment by Fruithapje21** [comment]
The problem here is pretty obvious and has to do with the formatting of pchtxt file. No offence but you maybe want to read the [documentation](https://github.com/3096/ipswitch/blob/master/example/README.md) and properly test stuff first because as I'm looking through the commits, none of the files from v4 onwards would actually work. Once you set the @enabled flag, the IPSwitchCompiler starts reading and it **only expects an offset and a value**. If you try to load comments, line breaks or whatever in between it will just stop reading. The yuzu log also clearly shows that only the first three instructions were patched (using the patches created by the latest version):
![Screenshot 2023-07-26 232737](https://github.com/fayaz12g/totk-aar/assets/136446038/7241e5e6-b03f-416d-b2ab-eb4ba38bcd88)

The easiest fix is to just enclose every patch in its own enabled/stop block. The better way would be to create a template for each game version and fill in the placeholders depending on what the user selected. To give you an idea what I mean I have added an example in this comment. Note the '@{statusX}' for every optional patch, which you can either replace with @enabled or @disabled depending on the user input. Patches starting with @disabled to not get applied. If you are lazy you can copy the templates from me and add your own needs into it.
[main-1.2.0.txt](https://github.com/fayaz12g/totk-aar/files/12177447/main-1.2.0.txt)

**Comment by InterClaw** [comment]
I took out all the comments and line breaks from my generated one for now and it seems to be working great! Noticing some other changes as well now hehe.

**Comment by fayaz12g** [comment]
@Fruithapje21 Thank you for explaining that all to me, I've never worked with this before. I always thought that including the "//" would comment out a line and it would skip it when reading. Before seeing these comments, I did a lot of testing with it today over zoom with my friend (as I still don't have access to yuzu for another week) and after yuzu crashing many times finally got it working by removing comments, I didn't know line breaks would also cause an issue though, which is currently how all of the visuals are built. I'll rebuild it in a way similar to what you mentioned at the end, as when I tried enclosing everything in a @enabled and @stop yuzu was crashing.  I'll work on getting a version that generates without line breaks and comments out tomorrow. I just released my fixes from today which have the Disable Quality Reduction and LOD Improvement on by default as well as a lot of fixes for the way images display now no longer being squished in the load game menu, save game menu, image saving menu, and the compendium saving menu.

**Comment by fayaz12g** [comment]
Okay @Fruithapje21 @InterClaw I just worked on a new version that makes use of the disabled tags including all the features but only turning them on with the enabled tag if they are checked. This new method also uses no line breaks and has enabled and stop tags around every line of code so it should work. It is version 8.4.0
