### ISSUE TITLE
Script.py new fixes

### ISSUE THREAD

**Issue by Fruithapje21** [fayaz12g/totk-aar#60]
I had a look at the new changes you've made in the script.py file. A lot of the changes just straight up break stuff and don't fix anything, but some are actually quite useful.

AppMap_00: You really should not touch this. It just breaks things.
SystemSaveLoad_00 and SystemLoadList_00: not sure what the idea was but you can not scale the images if that's what you are after. Also, any changes that do not include a scaling factor in their value make no sense. See broken saving screen:
![Screenshot 2023-07-29 154418](https://github.com/fayaz12g/totk-aar/assets/136446038/357f31bc-83ba-4e93-aa56-b58e5956d1ae)
CameraSystemWindow_00: I actually quite like this. Only picture related issue left is the compendium I guess. Probably won't be fixable as it will also include regular 16:9 pictures if you buy them from Robbie.
CameraPointer_00: This one really breaks a lot of stuff I feel like. Not only is everything stretched again, the object identifier also doesn't work properly anymore.
![Screenshot 2023-07-29 154321](https://github.com/fayaz12g/totk-aar/assets/136446038/9fca9bb3-081b-4066-b8ea-f734435f3310)

I'm also not sure why you have an expand_shutter option. I was confused and so are 99% of people I think. I scaled the scope in y direction to make it circular again like you did and it looks good to me. I would just remove the option for simplicity and make the y stretching the default.

Summary; Copied the CameraSystemWindow_00 and scope y stretching. Discarded the rest.
https://github.com/Fruithapje21/TOTK-Ultrawide/blob/main/romfs_script.py

**Comment by fayaz12g** [comment]
Finally got a chance to come back to this, sorry for the delay. 
SystemSaveLoad_00 and SystemLoadList_00: Yes the intention was the scale the image, which was working correctly on 21:9 for me, and I just added new lines to inversely scale the text as well which should fix that, and I will look for what is responsible for the saving icon and do that too. Initially I was able to ONLY scale the image, but then the image was too large and didn't fix in the box so I scaled the box too and compressed the components. I shifted the elements per 21:9 as I tinker with it to find the sweet spot, and was going to do the actual calculations after I find a good place for them to go.

CameraSystemWindow_00: Thank you, this was a change I was planning on doing for a few weeks but kept forgetting about it, but your new code format makes it a lot easier to quickly tinker with elements and test it so I finally did it. When I incorporated this, my friend told me about the pictures you buy from Robbie, as in his save he had these, so I was hesitant on changing the compendium, but I think I'll write a script that squishes all those images from the games files, then puts them onto a black canvas of the correct dimensions, so it will display a letterboxed image for ones you buy, and normal for ones you take (to keep the centering accurate)

CameraPointer_00: I stretched the RootPane by y and elements inversely as I thought in order to scale a component, the RootPane first had to fit it. I incorporated this as I was always bothered that the scope was stretched into an oval. My initial fix was to inversely squish it back into a circle with black bars on the sides, but if people thought that made it to small, to include the option to keep it expanded with expand_shutter. Then I realized I could just scale it by y, and made that the default. I now just have it listed in the tool as a feature to remove the scope mask entirely.
