### ISSUE TITLE
Odyssey (1.0.0)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#76]
I'm on version 1.3.0 of the game.

Found 2 things that are problematic:

1. There is a missing "Playing in VR" option on the main menu, both at the start and in game. If trying to navigate to the missing entry the game freezes. Yuzu itself is still responsive though.
2. Map does not take advantage of the wider aspect ratio, so you can "paint" that area when moving the map around.

Other than that I haven't found anything. I haven't really touched this game before, so not that familiar with it.

**Comment by fayaz12g** [comment]
Thank you so much for trying it out despite not having played the game before! Interesting that the VR option is missing, I never thought about it because I assumed VR support wouldn't work on yuzu given a pc is not a handle held with a gyroscope haha. 

As for the map, that's a great place for me to start doing manual fixes! I know that and the menus don't fill up the screen and instead just stay centered, so I'll see if I can change that. 

I wish I could move this issue to the GitHub repository hosting the smo-aar files, I want to keep it open while I work on it, if you don't mind could you copy and paste it into an issue there? I'll try to get to it this weekend, right now I'm working on split screen detection logic to adjust the aspect ratio for MK8D :)
