### ISSUE TITLE
3D space stretched in 1.2.1 (UI OK)

### ISSUE THREAD

**Issue by InterClaw** [fayaz12g/totk-aar#77]
In version 1.2.1 of the game the 3D world is 16:9 stretched out. Also Link in the menu is stretched.

But all UI elements look correct still, including the main menu when starting the game, the map etc.

(Also, dFPS is broken in this version, but it seems Chuck is [working on an update](https://www.reddit.com/user/ChucksFeedAndSeed/comments/14xksce/comment/ju8qqth/)? Beta7 perhaps?)

**Comment by fayaz12g** [comment]
I spent a few hours on this today and seemed to have found the address in 1.2.1 but it is not working. Hopefully Fruit will look at this as I'm not sure what I'm doing wrong. In Ghidra I'm finding 037f87fc to be the replacement value in 1.2.1, but it isn't working. I went back to the start with Cheat Engine to do it from scratch and found an address that changes the aspect ratio, and added the relative address to the new heap of 0x2105e00000 but gdb prints out a different value at the address I check. So yeah not sure what's wrong but for now stay on 1.2.0 if you can

**Comment by fayaz12g** [comment]
Alright, after a few hours of things not working I've got a workaround solution, it works in 1.2.1 with updated visual fixes and the 3d world is fixed, but link the menu is stretched and its using the older fmov asm code with the rounded ratio. Hopefully Fruit updates his code because he is a LOT smarter than me haha. As for dFPS, yeah I saw Chuck's comment, hopefully he'll release something soon.
