### ISSUE TITLE
Super Smash Bros Ultimate stuck in extracting zip

### ISSUE THREAD

**Issue by willsy32** [fayaz12g/totk-aar#82]
Love the new update by the way!  Some games such as SSBU get stuck in "extracting zip to .../romfs. This can also take a few seconds."  This is the only game that would replicate the same issue no matter what settings were chosen in UI. New update works great otherwise!  Love to see you're still working on it and adding new additions.

**Comment by fayaz12g** [comment]
Thanks for the kind words! Yes this is known because the file it tries to download for smash is 800MB 😬. The tool works (albeit without hud shifting, as with a few of the other new ones), but not only can I not host such a large file on GitHub, but I'm sure users do not want to wait for almost a gb to download and be stored in their mod folder. The existent mod uses an exefs patch for some of the menus, which is likely the better way to go about it and I'll look into it more eventually!

**Comment by willsy32** [comment]
> Thanks for the kind words! Yes this is known because the file it tries to download for smash is 800MB 😬. The tool works (albeit without hud shifting, as with a few of the other new ones), but not only can I not host such a large file on GitHub, but I'm sure users do not want to wait for almost a gb to download and be stored in their mod folder. The existent mod uses an exefs patch for some of the menus, which is likely the better way to go about it and I'll look into it more eventually!

I mean, If i need to download the file from a megaupload or google drive I'm cool with it lol.  Just looking to make a 4:3 aspect ratio for my crt monitor.  Thanks for the release either way!  Been really enjoying the other games in 4:3

**Comment by fayaz12g** [comment]
Glad to hear! I can 100% upload the files for you, the tool will work if it recognizes the files in the AppData folder (in AppData/Roaming/AnyAspectRatio it makes a folder for each tool's code, and then under "perm" it stores the base files that get adjusted, so I can send you the zips, I'll upload them sometime this week, and then you just place them in the respective folder, i.e perm/ssbu)

**Comment by fayaz12g** [comment]
actually, better solution idk why i didnt think of this, I can go ahead and generate 4:3 since I already have the files in the right place haha, hopefully it works I'll keep you updates

**Comment by willsy32** [comment]
> actually, better solution idk why i didnt think of this, I can go ahead and generate 4:3 since I already have the files in the right place haha, hopefully it works I'll keep you updates

Thank you so much!

**Comment by fayaz12g** [comment]
I am so sorry for not responding sooner. I seem to be having some issues with the hud fix files I generate, as they are not being read by the emulator. I can send you the exefs that fixes the 3D aspect ratio but I assume you already have that

**Comment by willsy32** [comment]
> I am so sorry for not responding sooner. I seem to be having some issues with the hud fix files I generate, as they are not being read by the emulator. I can send you the exefs that fixes the 3D aspect ratio but I assume you already have that

I think you're replying to the wrong issue? But I am curious if you have a 4:3 aspect ratio for smash yet?

**Comment by fayaz12g** [comment]
No did mean to reply here, I generated the 4:3 aspect ratio for smash with all the menus and everything, but but for some odd reason it did not work, and still shows 16:9 in game as the files did not scale the RootPanes (originally it would not launch, but I was able to work past that). I am still testing some things, but as I mentioned, I can send the fix for the 3D aspect ratio, it is actually quite simple and light, but all the UI is still stretched and I'm trying to figure it out
