### ISSUE TITLE
Not working on deck // And How-to for 3.1.0

### ISSUE THREAD

**Issue by PunkyBust** [fayaz12g/totk-aar#9]
Hello,

Many thank for this sharing, so amazing. 😀 
I've two little questions :)

  - On the last version linked on gamebanana, it pointed on 3.1.0, but on this version there is not executable just python script.
  So do I have to merge version 3.0.0 with 3.1.0 to use the application in the good way ? After merge the two version, with the controler file already in it, the tools just get an file not found when click on patch and same on 3.0.0. not merged.

- I'm on deck, and on 3.1.0 I see an scriptdeck.py, is this meen I can use your tool directly on my deck ?
Because for the 3 0.0 it is not working. Just create an empty folder.

Just to know if it cannot work on deck, and I have to do it exclusively on my pc.

Thank you very much.

**Comment by fayaz12g** [comment]
Hey! To answer your questions:
1. Use the Exe in v3. v3.1 was bugged hence when I removed the Exe so people would not use it. You only need the 14mb zip, not the controller files. The error you ran into could be because you do not have python 3.11 from the Microsoft store installed.
2. The current version does not work on steam deck. That script is meant for the steam deck aspect ratio for vertical stretching. It only runs via the exe

**Comment by PunkyBust** [comment]
Hello
Great, thank for this detail feedback.
Definitely linked to python version indeed.

Many thanks for this tool and your support ! 😀

**Comment by fayaz12g** [comment]
New version doesn't require python anymore :)
